let dog = {};
console.log(dog);
dog.name = "Basar";
dog.age = 2;
dog.uulder = "unknown";
dog.color = "black";
dog.impressingThing = "suul";
console.log(dog.name);
console.log(dog.age);
console.log(dog.uulder);
console.log(dog.color);
console.log(dog.impressingThing);
